default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: vacay_development

test:
  <<: *default
  database: vacay_test

production:
  <<: *default
  database: vacay_production